---
# some client tools to work with k8s
- name: Install client tools for kubernetes
  aur:
    name: "{{ item }}"
    state: present
  with_items:
    - kubelet-bin
    - kubeadm-bin
    - minikube-bin
    - kargo-cli
  become: True
  become_user: "{{ user.name }}"
