---
- name: Install VirtualBox and dependencies
  pacman: name={{ item }} state=present
  with_items:
    - net-tools
    - qt4
    - virtualbox
    - virtualbox-guest-iso
    - virtualbox-host-dkms
    - linux-headers

- name: Install VirtualBox extensions
  aur: name=virtualbox-ext-oracle
  become: True
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Add the user to vboxusers group
  user: name={{ user.name }} groups=vboxusers append=yes
