---
- name: Install beets and dependencies
  pacman: name={{ item }} state=present
  with_items:
    - gst-libav
    - gst-plugins-bad
    - gst-plugins-good
    - gst-plugins-ugly
    - gst-python
    - python-beautifulsoup4
    - python-gobject
    - python-pylast
    - python-requests
    - beets
  tags:
    - beets

- name: Install python-pyacoustid
  aur: name=python-pyacoustid
  become: True
  become_user: "{{ user.name }}"
  tags:
    - aur
    - beets

- name: Install mp3val
  aur: name=mp3val
  become: True
  become_user: "{{ user.name }}"
  tags:
    - aur
    - beets
