---
- name: Install universal base packages
  pacman:
    name: "{{ base_packages }}"
    state: present
  tags:
    - packages

- name: Create pacman hook directory
  file: path=/etc/pacman.d/hooks
        state=directory
  tags:
    - packages

- name: Push pacman mirror list update hook
  copy: src=mirrorlist.hook dest=/etc/pacman.d/hooks/mirrorlist.hook
  tags:
    - packages

- name: Create AUR directory
  file: path=/home/{{ user.name }}/{{ aur.dir }}
        state=directory
        owner={{ user.name }}
        group={{ user.group }}
  tags:
    - aur
    - packages

- name: Install AUR bootstrap packages
  include_role:
    name: base
    tasks_from: aur_bootstrap
  vars:
    pkg_name: "{{ item.name }}"
    gpg_key: "{{ item.gpg_key }}"
  with_items:
    - name: cower
      gpg_key: '1EB2638FF56C0C53'
    - name: trizen
      gpg_key: ''
  tags:
    - aur
    - packages

- name: Install AUR base packages
  aur:
    name: "{{ item }}"
  become: True
  become_user: "{{ user.name }}"
  with_items: "{{ aur.packages }}"
  tags:
    - aur
    - packages

- name: Push pacman cache cleanup service
  copy: src=paccache.service dest=/etc/systemd/system/paccache.service
  notify:
    - reload systemd config
  tags:
    - packages

- name: Push pacman cache cleanup timer
  copy: src=paccache.timer dest=/etc/systemd/system/paccache.timer
  notify:
    - reload systemd config
    - restart paccache
  tags:
    - packages

- name: Enable and start pacman cache cleanup timer
  service: name=paccache.timer enabled=yes state=started
  tags:
    - packages
